//HintName: ConfigHelpConstants.g.cs
// <auto-generated>
//     Generated by the ConfigHelpConstantsGenerator
// </auto-generated>
namespace Foo.Bar
{
    public static partial class Arena
    {
        public static partial class MySection
        {
            public static partial class MyKey
            {
                public const string Default = "MyDefaultValue";
            }
        }
        public static partial class Soccer
        {
            public static partial class NewGameDelay
            {
                public const int Default = -3000;
            }
        }
    }
}
namespace Foo.Bar
{
    internal static partial class Baz
    {
    }
}
namespace Foo.Bar
{
    public static partial class Global
    {
    }
}
