//HintName: ConfigHelpConstants.g.cs
// <auto-generated>
//     Generated by the ConfigHelpConstantsGenerator
// </auto-generated>
namespace Foo.Bar
{
    public static partial class TestGenerate
    {
        public static partial class Foo
        {
            public static partial class Bar
            {
                public const int Default = 123;
            }
        }
    }
}
