//HintName: ConfigHelpConstants.g.cs
// <auto-generated>
//     Generated by the ConfigHelpConstantsGenerator
// </auto-generated>
namespace Foo.Bar
{
    public static partial class Arena
    {
        public static partial class MySection
        {
            public static partial class @mykey
            {
                public const string Default = "MyDefaultValue";
            }
        }
    }
}
namespace Foo.Bar
{
    public static partial class Baz
    {
    }
}
namespace Foo.Bar
{
    public static partial class Global
    {
    }
}
