// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Chat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SS.Core.Persist.Protobuf {

  /// <summary>Holder for reflection information generated from Chat.proto</summary>
  public static partial class ChatReflection {

    #region Descriptor
    /// <summary>File descriptor for Chat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpDaGF0LnByb3RvEhhzcy5jb3JlLnBlcnNpc3QucHJvdG9idWYaH2dvb2ds",
            "ZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8iigEKCENoYXRNYXNrEgwKBG1h",
            "c2sYASABKAUSKwoHZXhwaXJlcxgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5U",
            "aW1lc3RhbXASFAoMbWVzc2FnZUNvdW50GAMgASgFEi0KCWxhc3RDaGVjaxgE",
            "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCG6oCGFNTLkNvcmUu",
            "UGVyc2lzdC5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SS.Core.Persist.Protobuf.ChatMask), global::SS.Core.Persist.Protobuf.ChatMask.Parser, new[]{ "Mask", "Expires", "MessageCount", "LastCheck" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChatMask : pb::IMessage<ChatMask>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChatMask> _parser = new pb::MessageParser<ChatMask>(() => new ChatMask());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChatMask> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SS.Core.Persist.Protobuf.ChatReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatMask() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatMask(ChatMask other) : this() {
      mask_ = other.mask_;
      expires_ = other.expires_ != null ? other.expires_.Clone() : null;
      messageCount_ = other.messageCount_;
      lastCheck_ = other.lastCheck_ != null ? other.lastCheck_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatMask Clone() {
      return new ChatMask(this);
    }

    /// <summary>Field number for the "mask" field.</summary>
    public const int MaskFieldNumber = 1;
    private int mask_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Mask {
      get { return mask_; }
      set {
        mask_ = value;
      }
    }

    /// <summary>Field number for the "expires" field.</summary>
    public const int ExpiresFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp expires_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Expires {
      get { return expires_; }
      set {
        expires_ = value;
      }
    }

    /// <summary>Field number for the "messageCount" field.</summary>
    public const int MessageCountFieldNumber = 3;
    private int messageCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MessageCount {
      get { return messageCount_; }
      set {
        messageCount_ = value;
      }
    }

    /// <summary>Field number for the "lastCheck" field.</summary>
    public const int LastCheckFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastCheck_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastCheck {
      get { return lastCheck_; }
      set {
        lastCheck_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChatMask);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChatMask other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mask != other.Mask) return false;
      if (!object.Equals(Expires, other.Expires)) return false;
      if (MessageCount != other.MessageCount) return false;
      if (!object.Equals(LastCheck, other.LastCheck)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Mask != 0) hash ^= Mask.GetHashCode();
      if (expires_ != null) hash ^= Expires.GetHashCode();
      if (MessageCount != 0) hash ^= MessageCount.GetHashCode();
      if (lastCheck_ != null) hash ^= LastCheck.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Mask != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Mask);
      }
      if (expires_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Expires);
      }
      if (MessageCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MessageCount);
      }
      if (lastCheck_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LastCheck);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Mask != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Mask);
      }
      if (expires_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Expires);
      }
      if (MessageCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MessageCount);
      }
      if (lastCheck_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LastCheck);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Mask != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Mask);
      }
      if (expires_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Expires);
      }
      if (MessageCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MessageCount);
      }
      if (lastCheck_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastCheck);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChatMask other) {
      if (other == null) {
        return;
      }
      if (other.Mask != 0) {
        Mask = other.Mask;
      }
      if (other.expires_ != null) {
        if (expires_ == null) {
          Expires = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Expires.MergeFrom(other.Expires);
      }
      if (other.MessageCount != 0) {
        MessageCount = other.MessageCount;
      }
      if (other.lastCheck_ != null) {
        if (lastCheck_ == null) {
          LastCheck = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastCheck.MergeFrom(other.LastCheck);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Mask = input.ReadInt32();
            break;
          }
          case 18: {
            if (expires_ == null) {
              Expires = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Expires);
            break;
          }
          case 24: {
            MessageCount = input.ReadInt32();
            break;
          }
          case 34: {
            if (lastCheck_ == null) {
              LastCheck = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastCheck);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Mask = input.ReadInt32();
            break;
          }
          case 18: {
            if (expires_ == null) {
              Expires = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Expires);
            break;
          }
          case 24: {
            MessageCount = input.ReadInt32();
            break;
          }
          case 34: {
            if (lastCheck_ == null) {
              LastCheck = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastCheck);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
