// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Stats.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SS.Core.Persist.Protobuf {

  /// <summary>Holder for reflection information generated from Stats.proto</summary>
  public static partial class StatsReflection {

    #region Descriptor
    /// <summary>File descriptor for Stats.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtTdGF0cy5wcm90bxIYc3MuY29yZS5wZXJzaXN0LnByb3RvYnVmGh5nb29n",
            "bGUvcHJvdG9idWYvZHVyYXRpb24ucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90",
            "aW1lc3RhbXAucHJvdG8i4QIKCFN0YXRJbmZvEhQKCmludDMyVmFsdWUYASAB",
            "KAVIABIVCgt1aW50MzJWYWx1ZRgCIAEoDUgAEhQKCmludDY0VmFsdWUYAyAB",
            "KANIABIVCgt1aW50NjRWYWx1ZRgEIAEoBEgAEhUKC3NpbnQzMlZhbHVlGAUg",
            "ASgRSAASFQoLc2ludDY0VmFsdWUYBiABKBJIABIWCgxmaXhlZDMyVmFsdWUY",
            "ByABKAdIABIWCgxmaXhlZDY0VmFsdWUYCCABKAZIABIXCg1zZml4ZWQzMlZh",
            "bHVlGAkgASgPSAASFwoNc2ZpeGVkNjRWYWx1ZRgKIAEoEEgAEi8KCXRpbWVz",
            "dGFtcBgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIABItCghk",
            "dXJhdGlvbhgMIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkgAQgsK",
            "CXN0YXRfaW5mbyKmAQoLUGxheWVyU3RhdHMSQwoHc3RhdE1hcBgBIAMoCzIy",
            "LnNzLmNvcmUucGVyc2lzdC5wcm90b2J1Zi5QbGF5ZXJTdGF0cy5TdGF0TWFw",
            "RW50cnkaUgoMU3RhdE1hcEVudHJ5EgsKA2tleRgBIAEoBRIxCgV2YWx1ZRgC",
            "IAEoCzIiLnNzLmNvcmUucGVyc2lzdC5wcm90b2J1Zi5TdGF0SW5mbzoCOAEi",
            "QQoKRW5kaW5nVGltZRIzCg9lbmRpbmdUaW1lc3RhbXAYASABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wQhuqAhhTUy5Db3JlLlBlcnNpc3QuUHJv",
            "dG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SS.Core.Persist.Protobuf.StatInfo), global::SS.Core.Persist.Protobuf.StatInfo.Parser, new[]{ "Int32Value", "Uint32Value", "Int64Value", "Uint64Value", "Sint32Value", "Sint64Value", "Fixed32Value", "Fixed64Value", "Sfixed32Value", "Sfixed64Value", "Timestamp", "Duration" }, new[]{ "StatInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SS.Core.Persist.Protobuf.PlayerStats), global::SS.Core.Persist.Protobuf.PlayerStats.Parser, new[]{ "StatMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::SS.Core.Persist.Protobuf.EndingTime), global::SS.Core.Persist.Protobuf.EndingTime.Parser, new[]{ "EndingTimestamp" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StatInfo : pb::IMessage<StatInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StatInfo> _parser = new pb::MessageParser<StatInfo>(() => new StatInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StatInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SS.Core.Persist.Protobuf.StatsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StatInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StatInfo(StatInfo other) : this() {
      switch (other.StatInfoCase) {
        case StatInfoOneofCase.Int32Value:
          Int32Value = other.Int32Value;
          break;
        case StatInfoOneofCase.Uint32Value:
          Uint32Value = other.Uint32Value;
          break;
        case StatInfoOneofCase.Int64Value:
          Int64Value = other.Int64Value;
          break;
        case StatInfoOneofCase.Uint64Value:
          Uint64Value = other.Uint64Value;
          break;
        case StatInfoOneofCase.Sint32Value:
          Sint32Value = other.Sint32Value;
          break;
        case StatInfoOneofCase.Sint64Value:
          Sint64Value = other.Sint64Value;
          break;
        case StatInfoOneofCase.Fixed32Value:
          Fixed32Value = other.Fixed32Value;
          break;
        case StatInfoOneofCase.Fixed64Value:
          Fixed64Value = other.Fixed64Value;
          break;
        case StatInfoOneofCase.Sfixed32Value:
          Sfixed32Value = other.Sfixed32Value;
          break;
        case StatInfoOneofCase.Sfixed64Value:
          Sfixed64Value = other.Sfixed64Value;
          break;
        case StatInfoOneofCase.Timestamp:
          Timestamp = other.Timestamp.Clone();
          break;
        case StatInfoOneofCase.Duration:
          Duration = other.Duration.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StatInfo Clone() {
      return new StatInfo(this);
    }

    /// <summary>Field number for the "int32Value" field.</summary>
    public const int Int32ValueFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Int32Value {
      get { return statInfoCase_ == StatInfoOneofCase.Int32Value ? (int) statInfo_ : 0; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Int32Value;
      }
    }

    /// <summary>Field number for the "uint32Value" field.</summary>
    public const int Uint32ValueFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Uint32Value {
      get { return statInfoCase_ == StatInfoOneofCase.Uint32Value ? (uint) statInfo_ : 0; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Uint32Value;
      }
    }

    /// <summary>Field number for the "int64Value" field.</summary>
    public const int Int64ValueFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Int64Value {
      get { return statInfoCase_ == StatInfoOneofCase.Int64Value ? (long) statInfo_ : 0L; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Int64Value;
      }
    }

    /// <summary>Field number for the "uint64Value" field.</summary>
    public const int Uint64ValueFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Uint64Value {
      get { return statInfoCase_ == StatInfoOneofCase.Uint64Value ? (ulong) statInfo_ : 0UL; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Uint64Value;
      }
    }

    /// <summary>Field number for the "sint32Value" field.</summary>
    public const int Sint32ValueFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sint32Value {
      get { return statInfoCase_ == StatInfoOneofCase.Sint32Value ? (int) statInfo_ : 0; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Sint32Value;
      }
    }

    /// <summary>Field number for the "sint64Value" field.</summary>
    public const int Sint64ValueFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sint64Value {
      get { return statInfoCase_ == StatInfoOneofCase.Sint64Value ? (long) statInfo_ : 0L; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Sint64Value;
      }
    }

    /// <summary>Field number for the "fixed32Value" field.</summary>
    public const int Fixed32ValueFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Fixed32Value {
      get { return statInfoCase_ == StatInfoOneofCase.Fixed32Value ? (uint) statInfo_ : 0; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Fixed32Value;
      }
    }

    /// <summary>Field number for the "fixed64Value" field.</summary>
    public const int Fixed64ValueFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Fixed64Value {
      get { return statInfoCase_ == StatInfoOneofCase.Fixed64Value ? (ulong) statInfo_ : 0UL; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Fixed64Value;
      }
    }

    /// <summary>Field number for the "sfixed32Value" field.</summary>
    public const int Sfixed32ValueFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sfixed32Value {
      get { return statInfoCase_ == StatInfoOneofCase.Sfixed32Value ? (int) statInfo_ : 0; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Sfixed32Value;
      }
    }

    /// <summary>Field number for the "sfixed64Value" field.</summary>
    public const int Sfixed64ValueFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sfixed64Value {
      get { return statInfoCase_ == StatInfoOneofCase.Sfixed64Value ? (long) statInfo_ : 0L; }
      set {
        statInfo_ = value;
        statInfoCase_ = StatInfoOneofCase.Sfixed64Value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return statInfoCase_ == StatInfoOneofCase.Timestamp ? (global::Google.Protobuf.WellKnownTypes.Timestamp) statInfo_ : null; }
      set {
        statInfo_ = value;
        statInfoCase_ = value == null ? StatInfoOneofCase.None : StatInfoOneofCase.Timestamp;
      }
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 12;
    /// <summary>
    ///double doubleValue = 14;
    ///float floatValue = 15;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Duration Duration {
      get { return statInfoCase_ == StatInfoOneofCase.Duration ? (global::Google.Protobuf.WellKnownTypes.Duration) statInfo_ : null; }
      set {
        statInfo_ = value;
        statInfoCase_ = value == null ? StatInfoOneofCase.None : StatInfoOneofCase.Duration;
      }
    }

    private object statInfo_;
    /// <summary>Enum of possible cases for the "stat_info" oneof.</summary>
    public enum StatInfoOneofCase {
      None = 0,
      Int32Value = 1,
      Uint32Value = 2,
      Int64Value = 3,
      Uint64Value = 4,
      Sint32Value = 5,
      Sint64Value = 6,
      Fixed32Value = 7,
      Fixed64Value = 8,
      Sfixed32Value = 9,
      Sfixed64Value = 10,
      Timestamp = 11,
      Duration = 12,
    }
    private StatInfoOneofCase statInfoCase_ = StatInfoOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StatInfoOneofCase StatInfoCase {
      get { return statInfoCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStatInfo() {
      statInfoCase_ = StatInfoOneofCase.None;
      statInfo_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StatInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StatInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Int32Value != other.Int32Value) return false;
      if (Uint32Value != other.Uint32Value) return false;
      if (Int64Value != other.Int64Value) return false;
      if (Uint64Value != other.Uint64Value) return false;
      if (Sint32Value != other.Sint32Value) return false;
      if (Sint64Value != other.Sint64Value) return false;
      if (Fixed32Value != other.Fixed32Value) return false;
      if (Fixed64Value != other.Fixed64Value) return false;
      if (Sfixed32Value != other.Sfixed32Value) return false;
      if (Sfixed64Value != other.Sfixed64Value) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (!object.Equals(Duration, other.Duration)) return false;
      if (StatInfoCase != other.StatInfoCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (statInfoCase_ == StatInfoOneofCase.Int32Value) hash ^= Int32Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Uint32Value) hash ^= Uint32Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Int64Value) hash ^= Int64Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Uint64Value) hash ^= Uint64Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Sint32Value) hash ^= Sint32Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Sint64Value) hash ^= Sint64Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Fixed32Value) hash ^= Fixed32Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Fixed64Value) hash ^= Fixed64Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Sfixed32Value) hash ^= Sfixed32Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Sfixed64Value) hash ^= Sfixed64Value.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Timestamp) hash ^= Timestamp.GetHashCode();
      if (statInfoCase_ == StatInfoOneofCase.Duration) hash ^= Duration.GetHashCode();
      hash ^= (int) statInfoCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (statInfoCase_ == StatInfoOneofCase.Int32Value) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Uint32Value) {
        output.WriteRawTag(16);
        output.WriteUInt32(Uint32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Int64Value) {
        output.WriteRawTag(24);
        output.WriteInt64(Int64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Uint64Value) {
        output.WriteRawTag(32);
        output.WriteUInt64(Uint64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sint32Value) {
        output.WriteRawTag(40);
        output.WriteSInt32(Sint32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sint64Value) {
        output.WriteRawTag(48);
        output.WriteSInt64(Sint64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Fixed32Value) {
        output.WriteRawTag(61);
        output.WriteFixed32(Fixed32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Fixed64Value) {
        output.WriteRawTag(65);
        output.WriteFixed64(Fixed64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sfixed32Value) {
        output.WriteRawTag(77);
        output.WriteSFixed32(Sfixed32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sfixed64Value) {
        output.WriteRawTag(81);
        output.WriteSFixed64(Sfixed64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Timestamp) {
        output.WriteRawTag(90);
        output.WriteMessage(Timestamp);
      }
      if (statInfoCase_ == StatInfoOneofCase.Duration) {
        output.WriteRawTag(98);
        output.WriteMessage(Duration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (statInfoCase_ == StatInfoOneofCase.Int32Value) {
        output.WriteRawTag(8);
        output.WriteInt32(Int32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Uint32Value) {
        output.WriteRawTag(16);
        output.WriteUInt32(Uint32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Int64Value) {
        output.WriteRawTag(24);
        output.WriteInt64(Int64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Uint64Value) {
        output.WriteRawTag(32);
        output.WriteUInt64(Uint64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sint32Value) {
        output.WriteRawTag(40);
        output.WriteSInt32(Sint32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sint64Value) {
        output.WriteRawTag(48);
        output.WriteSInt64(Sint64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Fixed32Value) {
        output.WriteRawTag(61);
        output.WriteFixed32(Fixed32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Fixed64Value) {
        output.WriteRawTag(65);
        output.WriteFixed64(Fixed64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sfixed32Value) {
        output.WriteRawTag(77);
        output.WriteSFixed32(Sfixed32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sfixed64Value) {
        output.WriteRawTag(81);
        output.WriteSFixed64(Sfixed64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Timestamp) {
        output.WriteRawTag(90);
        output.WriteMessage(Timestamp);
      }
      if (statInfoCase_ == StatInfoOneofCase.Duration) {
        output.WriteRawTag(98);
        output.WriteMessage(Duration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (statInfoCase_ == StatInfoOneofCase.Int32Value) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Uint32Value) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uint32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Int64Value) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Uint64Value) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uint64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sint32Value) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Sint32Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Sint64Value) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Sint64Value);
      }
      if (statInfoCase_ == StatInfoOneofCase.Fixed32Value) {
        size += 1 + 4;
      }
      if (statInfoCase_ == StatInfoOneofCase.Fixed64Value) {
        size += 1 + 8;
      }
      if (statInfoCase_ == StatInfoOneofCase.Sfixed32Value) {
        size += 1 + 4;
      }
      if (statInfoCase_ == StatInfoOneofCase.Sfixed64Value) {
        size += 1 + 8;
      }
      if (statInfoCase_ == StatInfoOneofCase.Timestamp) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (statInfoCase_ == StatInfoOneofCase.Duration) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Duration);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StatInfo other) {
      if (other == null) {
        return;
      }
      switch (other.StatInfoCase) {
        case StatInfoOneofCase.Int32Value:
          Int32Value = other.Int32Value;
          break;
        case StatInfoOneofCase.Uint32Value:
          Uint32Value = other.Uint32Value;
          break;
        case StatInfoOneofCase.Int64Value:
          Int64Value = other.Int64Value;
          break;
        case StatInfoOneofCase.Uint64Value:
          Uint64Value = other.Uint64Value;
          break;
        case StatInfoOneofCase.Sint32Value:
          Sint32Value = other.Sint32Value;
          break;
        case StatInfoOneofCase.Sint64Value:
          Sint64Value = other.Sint64Value;
          break;
        case StatInfoOneofCase.Fixed32Value:
          Fixed32Value = other.Fixed32Value;
          break;
        case StatInfoOneofCase.Fixed64Value:
          Fixed64Value = other.Fixed64Value;
          break;
        case StatInfoOneofCase.Sfixed32Value:
          Sfixed32Value = other.Sfixed32Value;
          break;
        case StatInfoOneofCase.Sfixed64Value:
          Sfixed64Value = other.Sfixed64Value;
          break;
        case StatInfoOneofCase.Timestamp:
          if (Timestamp == null) {
            Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          Timestamp.MergeFrom(other.Timestamp);
          break;
        case StatInfoOneofCase.Duration:
          if (Duration == null) {
            Duration = new global::Google.Protobuf.WellKnownTypes.Duration();
          }
          Duration.MergeFrom(other.Duration);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Int32Value = input.ReadInt32();
            break;
          }
          case 16: {
            Uint32Value = input.ReadUInt32();
            break;
          }
          case 24: {
            Int64Value = input.ReadInt64();
            break;
          }
          case 32: {
            Uint64Value = input.ReadUInt64();
            break;
          }
          case 40: {
            Sint32Value = input.ReadSInt32();
            break;
          }
          case 48: {
            Sint64Value = input.ReadSInt64();
            break;
          }
          case 61: {
            Fixed32Value = input.ReadFixed32();
            break;
          }
          case 65: {
            Fixed64Value = input.ReadFixed64();
            break;
          }
          case 77: {
            Sfixed32Value = input.ReadSFixed32();
            break;
          }
          case 81: {
            Sfixed64Value = input.ReadSFixed64();
            break;
          }
          case 90: {
            global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            if (statInfoCase_ == StatInfoOneofCase.Timestamp) {
              subBuilder.MergeFrom(Timestamp);
            }
            input.ReadMessage(subBuilder);
            Timestamp = subBuilder;
            break;
          }
          case 98: {
            global::Google.Protobuf.WellKnownTypes.Duration subBuilder = new global::Google.Protobuf.WellKnownTypes.Duration();
            if (statInfoCase_ == StatInfoOneofCase.Duration) {
              subBuilder.MergeFrom(Duration);
            }
            input.ReadMessage(subBuilder);
            Duration = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Int32Value = input.ReadInt32();
            break;
          }
          case 16: {
            Uint32Value = input.ReadUInt32();
            break;
          }
          case 24: {
            Int64Value = input.ReadInt64();
            break;
          }
          case 32: {
            Uint64Value = input.ReadUInt64();
            break;
          }
          case 40: {
            Sint32Value = input.ReadSInt32();
            break;
          }
          case 48: {
            Sint64Value = input.ReadSInt64();
            break;
          }
          case 61: {
            Fixed32Value = input.ReadFixed32();
            break;
          }
          case 65: {
            Fixed64Value = input.ReadFixed64();
            break;
          }
          case 77: {
            Sfixed32Value = input.ReadSFixed32();
            break;
          }
          case 81: {
            Sfixed64Value = input.ReadSFixed64();
            break;
          }
          case 90: {
            global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            if (statInfoCase_ == StatInfoOneofCase.Timestamp) {
              subBuilder.MergeFrom(Timestamp);
            }
            input.ReadMessage(subBuilder);
            Timestamp = subBuilder;
            break;
          }
          case 98: {
            global::Google.Protobuf.WellKnownTypes.Duration subBuilder = new global::Google.Protobuf.WellKnownTypes.Duration();
            if (statInfoCase_ == StatInfoOneofCase.Duration) {
              subBuilder.MergeFrom(Duration);
            }
            input.ReadMessage(subBuilder);
            Duration = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PlayerStats : pb::IMessage<PlayerStats>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerStats> _parser = new pb::MessageParser<PlayerStats>(() => new PlayerStats());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerStats> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SS.Core.Persist.Protobuf.StatsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerStats() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerStats(PlayerStats other) : this() {
      statMap_ = other.statMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerStats Clone() {
      return new PlayerStats(this);
    }

    /// <summary>Field number for the "statMap" field.</summary>
    public const int StatMapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::SS.Core.Persist.Protobuf.StatInfo>.Codec _map_statMap_codec
        = new pbc::MapField<int, global::SS.Core.Persist.Protobuf.StatInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::SS.Core.Persist.Protobuf.StatInfo.Parser), 10);
    private readonly pbc::MapField<int, global::SS.Core.Persist.Protobuf.StatInfo> statMap_ = new pbc::MapField<int, global::SS.Core.Persist.Protobuf.StatInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::SS.Core.Persist.Protobuf.StatInfo> StatMap {
      get { return statMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerStats);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerStats other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!StatMap.Equals(other.StatMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= StatMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      statMap_.WriteTo(output, _map_statMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      statMap_.WriteTo(ref output, _map_statMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += statMap_.CalculateSize(_map_statMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerStats other) {
      if (other == null) {
        return;
      }
      statMap_.Add(other.statMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            statMap_.AddEntriesFrom(input, _map_statMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            statMap_.AddEntriesFrom(ref input, _map_statMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EndingTime : pb::IMessage<EndingTime>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EndingTime> _parser = new pb::MessageParser<EndingTime>(() => new EndingTime());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EndingTime> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SS.Core.Persist.Protobuf.StatsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EndingTime() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EndingTime(EndingTime other) : this() {
      endingTimestamp_ = other.endingTimestamp_ != null ? other.endingTimestamp_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EndingTime Clone() {
      return new EndingTime(this);
    }

    /// <summary>Field number for the "endingTimestamp" field.</summary>
    public const int EndingTimestampFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp endingTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp EndingTimestamp {
      get { return endingTimestamp_; }
      set {
        endingTimestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EndingTime);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EndingTime other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EndingTimestamp, other.EndingTimestamp)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (endingTimestamp_ != null) hash ^= EndingTimestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (endingTimestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EndingTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (endingTimestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EndingTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (endingTimestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndingTimestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EndingTime other) {
      if (other == null) {
        return;
      }
      if (other.endingTimestamp_ != null) {
        if (endingTimestamp_ == null) {
          EndingTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        EndingTimestamp.MergeFrom(other.EndingTimestamp);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (endingTimestamp_ == null) {
              EndingTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(EndingTimestamp);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (endingTimestamp_ == null) {
              EndingTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(EndingTimestamp);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
